import React from 'react'
import { NavLink } from 'react-router-dom'

const nav = [
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Dashboard',
    to: '/dashboard',
    icon: 'nav-icon fas fa-tachometer-alt',
    module: 1,
    role: 1,
    badge: {
      color: 'info',
      text: 'NEW',
    },
  },
  {
    _component: 'CNavTitle',
    anchor: 'Set Up',
    level: 0,
  },
  {
    _component: 'CNavGroup',
    as: NavLink,
    anchor: 'icon',
    to: '/icon',
    icon: 'nav-icon fas fa-th',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'icon',
        to: '/icon',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'notifications',
        to: '/notifications',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'table',
        to: '/table',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'typography',
    to: '/typography',
    icon: 'nav-icon far fa-image',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'typography',
        to: '/typography',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'upgrade',
        to: '/upgrade',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'user',
        to: '/user',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Layout Options',
    to: '/dashboard',
    icon: 'nav-icon fas fa-copy',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Charts',
    to: '/dashboard',
    icon: 'nav-icon fas fa-chart-pie',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  },
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'UI Elements',
    to: '/dashboard',
    icon: 'nav-icon fas fa-tree',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Forms',
    to: '/dashboard',
    icon: 'nav-icon fas fa-edit',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Table',
    to: '/dashboard',
    icon: 'nav-icon fas fa-table',
    module: 1,
    role: 1,
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Calendar',
    to: '/dashboard',
    icon: 'nav-icon far fa-calendar-alt',
    module: 1,
    role: 1,
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Kanban Board',
    to: '/dashboard',
    icon: 'nav-icon fas fa-columns',
    module: 1,
    role: 1,
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Mailbox',
    to: '/dashboard',
    icon: 'nav-icon fas far fa-envelope',
    module: 1,
    role: 1,
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Pages',
    to: '/dashboard',
    icon: 'nav-icon fas fa-book',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  }, 
  {
    _component: 'CNavItem',
    as: NavLink,
    anchor: 'Extras',
    to: '/dashboard',
    icon: 'nav-icon far fa-plus-square',
    module: 1,
    role: 1,
    child: 'right fas fa-angle-left',
    items: [
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Accordion',
        to: '/base/accordion',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Breadcrumb',
        to: '/base/breadcrumbs',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
      {
        _component: 'CNavItem',
        as: NavLink,
        anchor: 'Cards',
        to: '/base/cards',
        icon: 'far fa-circle nav-icon',
        module: 1,
        role: 1,
      },
    ],
  },

]

export default nav